### ISSUE TITLE
2.1.2 踊り字「々」が表外漢字として報告される

### ISSUE THREAD

**Issue by momdo** [azu/textlint-rule-preset-JTF-style#48]
「々」は記号であって漢字ではない（Unicodeで言うところのCjk Symbols And Punctuation）ので、エラーとして報告させないのが正しいと思います。

参考情報：
https://ja.wikipedia.org/wiki/%E8%B8%8A%E3%82%8A%E5%AD%97
https://www.compart.com/en/unicode/U+3005

**Comment by azu** [comment]
ありがとうございます。"々"を除外した[2.2.2](https://github.com/azu/textlint-rule-preset-JTF-style/releases/tag/2.2.2 "2.2.2")をリリースしました
