### ISSUE TITLE
4.3.5: HTMLプラグインとの組み合わせで誤ってエラーが報告される

### ISSUE THREAD

**Issue by momdo** [azu/textlint-rule-preset-JTF-style#49]
textlint-plugin-htmlプラグインと併用する場合に、例えば

```html
"<code>code</code>"
````

のようなHTMLフラグメントでエラーが報告されます。

**Comment by azu** [comment]
```html
<p>"<code>code</code>"</p>
```

であるならば認識はできるのですが、現在の実装だと

```
String1 Code String2
```

という要素の並びなので、String1とString2が同じ文(Paragraph)であるのかがわからないのが原因ですね。(Paragraphないで対応があるかを見ている)

**Comment by azu** [comment]
https://github.com/azu/textlint-rule-preset-JTF-style/blob/c81125a619f4c1ecd3cd81fbb4722c29a9bcf63f/src/util/pair-checker.js

あー、これ実装が少し変な気がしますね。
`"` みたいに対の記号が同じものだとおかしくなりますね

**Comment by azu** [comment]
> <p>"<code>code</code>"</p>

こちらは正しく認識するようにした https://github.com/azu/textlint-rule-preset-JTF-style/releases/tag/2.2.3 を出しました。

> "<code>code</code>"

は今のところいい実装方法がないなら仕様ですね。

**Comment by momdo** [comment]
早速の対応ありがとうございます。「裸の」`"<code>code</code>"`は実際のHTML文書でまず遭遇しないと思うので、実用上は問題ないと思います（例示はそこまで深く考えずにしたものなので）。
